name: "Build"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '44 5 * * 0'

jobs:
  build:
    name: Build
    runs-on: Linux
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build


    #- name: Nginx
    #  run: |
    #    sudo rm -rf /usr/share/nginx/chat-front/html/*
    #    sudo cp -r ./dist/* /usr/share/nginx/chat-front/html
    #    sudo chmod -R 777 /usr/share/nginx/chat-front/html

    - name: Upload build
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: dist

    - name: Dockerfile build
      run: |
        docker login -u karasus15 -p ${{ secrets.DOCKER_PASSWORD }}
        docker build -t chat-front .
        docker tag chat-front karasus15/ee2e-chat-frontend:latest
        docker push karasus15/ee2e-chat-frontend:latest

    - name: Delete pod
      run: |
        kubectl delete pod -l app=ee2e-chat-frontend-vue
        kubectl get pods -l app=ee2e-chat-frontend-vue